"use strict";

const max_guesses = 9;
const hint_text = document.getElementById("hint-text");
const guess_input = document.getElementById("guess-input");
const displayed_letters = document.getElementById("guessed-letters");
const guess_counter = document.getElementById("guess-count");
const guess_display = document.getElementById("guessed-word");
const score_counter = document.getElementById("score-count");
const submit_button = document.getElementById("submit-button");
const timer = document.getElementById("timer");
const timer_update_ms = 500;

let game_running = false;
let word = "";
let guessed_word = "";
let guessed_letters = new Set();
let num_incorrect = 0;
let time_start = new Date();
let interval = -1;

function calculate_score() {
    const guess_penalty = 1 + num_incorrect;
    const time_penalty = 1 + elapsed_time_sec();
    return Math.floor(1000 * word.length / (guess_penalty * time_penalty));
}

function elapsed_time_sec() {
    return Math.round((new Date() - time_start) / 1000);
}

// Autogenerated with help of https://randomwordgenerator.com/
const words = ["variation","awareness","basket","dinner","memory","power","version","explanation","negotiation","courage","restaurant","education","event","gene","shopping","hearing","preparation","context","software","lady","meaning","director","secretary","population","debt","son","child","advice","philosophy","role","sister","opinion","employee","client","police","department","video","disease","meal","honey","way","safety","environment","recommendation","selection","exam","insect","inflation","permission","mode","attitude","church","youth","chocolate","organization","proposal","cabinet","hearing","control","debt","tongue","possession","paper","poet","city","singer","property","mom","initiative","relationship","efficiency","permission","message","week","event","media","recording","elevator","failure","phone","union","product","county","assistance","philosophy","professor","editor","society","thing","steak","success","fact","engine","cheek","orange","injury","chemistry","moment","bedroom","student","hair","injury","girlfriend","cheek","town","response","soup","king","session","imagination","thing","moment","collection","payment","historian","queen","client","guest","message","performance","ad","insurance","variety","drawer","shirt","professor","entertainment","penalty","introduction","newspaper","article","flight","event","secretary","television","courage","understanding","employment","cell","appearance","climate","virus","language","solution","philosophy","failure","championship","uncle","driver","confusion"];

function display_elapsed_time() {
    let sec = elapsed_time_sec();
    let min = Math.floor(sec / 60);
    sec %= 60;
    timer.innerText = min === 0 ? `${sec}s` : `${min}m ${sec}s`;
    score_counter.value = calculate_score();
}

function new_hangman_game() {
    if (words.length === 0)
        return console.log("No words found!");
    for (let tile of document.getElementsByClassName("tile")) {
        tile.setAttribute("opaque", "true");
    }
    time_start = new Date();
    num_incorrect = 0;
    guessed_letters.clear();
    word = words[Math.floor(Math.random() * words.length)].toUpperCase();
    clearInterval(interval);
    interval = setInterval(display_elapsed_time, timer_update_ms);
    game_running = true;
    update_guess();
    // Reset the text for new games
    hint_text.innerText = "Guess a letter";
    displayed_letters.innerText = "--";
    guess_counter.innerText = `${num_incorrect} out of ${max_guesses}`;
    guess_input.value = "";
    display_elapsed_time();
    enable_guess_input();
    disable_save_score();
    guess_input.focus();
}

function show_tiles() {
    const tiles = document.querySelectorAll(".tile[opaque=true]");
    const letters_left = (guessed_word.match(/_/g) ?? []).length;
    const n = Math.ceil(max_guesses * letters_left / word.length);
    // Uncover the terrapin image based on ratio of letters correctly guessed
    for (let i = 0; i < tiles.length - n; ++i)
        tiles[i].setAttribute("opaque", "false");
}

function check_win_condition() {
    if (guessed_word !== word && num_incorrect < max_guesses)
        return disable_save_score();
    disable_guess_input();
    enable_save_score();
    guess_display.innerText = word;
    game_running = false;
    clearInterval(interval);
}

function update_guess() {
    guessed_word = word.split("").map((x) => guessed_letters.has(x) ? x : "_").join("");
    guess_display.innerText = guessed_word;
}

function guess_letter(letter) {
    if (!game_running)
        return;
    if (!(/^[A-Za-z]+$/.test(letter))) {
        // Prevent anything other than letters from being guessed
        hint_text.innerText = "Only letter guesses are valid";
        return;
    }
    if (guessed_letters.has(letter)) {
        // Prevent double guessing a letter
        hint_text.innerText = "Letter has already been guessed";
        return;
    }
    hint_text.innerText = "Guess a letter";
    if (word.indexOf(letter) === -1)
        guess_counter.innerText = `${++num_incorrect} out of ${max_guesses}`;
    guessed_letters.add(letter);
    let text = "";
    for (const letter of guessed_letters) {
        text += letter + " ";
    }
    displayed_letters.innerText = text;
    update_guess();
    check_win_condition();
}

function guess_letters(form_event) {
    form_event.preventDefault();
    let letters = guess_input.value.toUpperCase().split("");
    for (let letter of letters)
        guess_letter(letter);
    guess_input.value = "";
    show_tiles();
}

function enable_guess_input() {
    guess_input.removeAttribute("disabled");
}

function disable_guess_input() {
    guess_input.setAttribute("disabled", "");
}

function enable_save_score() {
    submit_button.removeAttribute("disabled");
}

function disable_save_score() {
    submit_button.setAttribute("disabled", "");
}

disable_guess_input();
disable_save_score();